# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mahasiswa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem, QMessageBox

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(444, 516)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 101, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.QlabelNPM = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.QlabelNPM.setObjectName("QlabelNPM")
        self.verticalLayout.addWidget(self.QlabelNPM)
        self.QlabelNama = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.QlabelNama.setObjectName("QlabelNama")
        self.verticalLayout.addWidget(self.QlabelNama)
        self.QlabelKelas = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.QlabelKelas.setObjectName("QlabelKelas")
        self.verticalLayout.addWidget(self.QlabelKelas)
        self.QlabelJurusan = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.QlabelJurusan.setObjectName("QlabelJurusan")
        self.verticalLayout.addWidget(self.QlabelJurusan)
        self.QlabelTanggalLahir = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.QlabelTanggalLahir.setObjectName("QlabelTanggalLahir")
        self.verticalLayout.addWidget(self.QlabelTanggalLahir)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(110, 10, 171, 111))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEditNPM = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditNPM.setObjectName("lineEditNPM")
        self.verticalLayout_2.addWidget(self.lineEditNPM)
        self.lineEditNAMA = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditNAMA.setObjectName("lineEditNAMA")
        self.verticalLayout_2.addWidget(self.lineEditNAMA)
        self.lineEditKelas = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditKelas.setObjectName("lineEditKelas")
        self.verticalLayout_2.addWidget(self.lineEditKelas)
        self.lineEditJurusan = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditJurusan.setObjectName("lineEditJurusan")
        self.verticalLayout_2.addWidget(self.lineEditJurusan)
        self.lineEditTanggalLahir = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditTanggalLahir.setObjectName("lineEditTanggalLahir")
        self.verticalLayout_2.addWidget(self.lineEditTanggalLahir)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 140, 391, 21))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonTambahkan = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonTambahkan.setObjectName("pushButtonTambahkan")
        self.horizontalLayout.addWidget(self.pushButtonTambahkan)
        self.pushButtonHapus = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonHapus.setObjectName("pushButtonHapus")
        self.horizontalLayout.addWidget(self.pushButtonHapus)
        self.pushButtonUbah = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonUbah.setObjectName("pushButtonUbah")
        self.horizontalLayout.addWidget(self.pushButtonUbah)
        self.pushButtonLoad = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.horizontalLayout.addWidget(self.pushButtonLoad)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 180, 391, 191))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.horizontalLayoutWidget_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.horizontalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 380, 61, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButtonSearch = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.horizontalLayout_4.addWidget(self.pushButtonSearch)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(70, 380, 160, 31))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEditSearch = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.verticalLayout_3.addWidget(self.lineEditSearch)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    
        self.pushButtonTambahkan.clicked.connect(self.insertmahasiswa)
        self.pushButtonHapus.clicked.connect(self.hapusmahasiswa)
        self.pushButtonUbah.clicked.connect(self.ubahmahasiswa)
        self.pushButtonLoad.clicked.connect(self.loadmahasiswa)
        self.pushButtonSearch.clicked.connect(self.searchmahasiswa)
        self.tableWidget.cellClicked.connect(self.on_table_item_clicked)

 
    def koneksi_db(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="dbkampus"
            )
            return mydb
        except mc.Error as e:
            QMessageBox.critical(None, "Database Error", f"Koneksi ke database gagal: {e}")
            return None

    def insertmahasiswa(self):
        try:
            mydb = self.koneksi_db()
            if not mydb:
                return
            cursor = mydb.cursor()
            sql = "INSERT INTO mahasiswa (npm, nama, kelas, jurusan, tanggal_lahir) VALUES (%s, %s, %s, %s, %s)"
            val = (
                self.lineEditNPM.text(),
                self.lineEditNAMA.text(),
                self.lineEditKelas.text(),
                self.lineEditJurusan.text(),
                self.lineEditTanggalLahir.text()
            )
            cursor.execute(sql, val)
            mydb.commit()
            QMessageBox.information(None, "Success", "Data mahasiswa berhasil ditambahkan")
            self.clear_form()
            self.loadmahasiswa()
        except mc.Error as e:
            QMessageBox.critical(None, "Error", f"Gagal menambahkan data: {e}")

    def loadmahasiswa(self):
        try:
            mydb = self.koneksi_db()
            if not mydb:
                return
            cursor = mydb.cursor()
            cursor.execute("SELECT * FROM mahasiswa")
            result = cursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))
        except mc.Error as e:
            QMessageBox.critical(None, "Error", f"Gagal memuat data: {e}")

    def hapusmahasiswa(self):
        try:
            selected_row = self.tableWidget.currentRow()
            if selected_row == -1:
                QMessageBox.warning(None, "Warning", "Pilih baris yang ingin dihapus")
                return
            npm = self.tableWidget.item(selected_row, 0).text()
            mydb = self.koneksi_db()
            if not mydb:
                return
            cursor = mydb.cursor()
            sql = "DELETE FROM mahasiswa WHERE npm = %s"
            cursor.execute(sql, (npm,))
            mydb.commit()
            QMessageBox.information(None, "Success", "Data mahasiswa berhasil dihapus")
            self.loadmahasiswa()
        except mc.Error as e:
            QMessageBox.critical(None, "Error", f"Gagal menghapus data: {e}")

    def ubahmahasiswa(self):
        try:
            selected_row = self.tableWidget.currentRow()
            if selected_row == -1:
                QMessageBox.warning(None, "Warning", "Pilih baris yang ingin diubah")
                return
            npm = self.tableWidget.item(selected_row, 0).text()
            mydb = self.koneksi_db()
            if not mydb:
                return
            cursor = mydb.cursor()
            sql = "UPDATE mahasiswa SET nama = %s, kelas = %s, jurusan = %s, tanggal_lahir = %s WHERE npm = %s"
            val = (
                self.lineEditNAMA.text(),
                self.lineEditKelas.text(),
                self.lineEditJurusan.text(),
                self.lineEditTanggalLahir.text(),
                npm
            )
            cursor.execute(sql, val)
            mydb.commit()
            QMessageBox.information(None, "Success", "Data mahasiswa berhasil diubah")
            self.clear_form()
            self.loadmahasiswa()
        except mc.Error as e:
            QMessageBox.critical(None, "Error", f"Gagal mengubah data: {e}")

    def searchmahasiswa(self):
        try:
            keyword = self.lineEditSearch.text()
            mydb = self.koneksi_db()
            if not mydb:
                return
            cursor = mydb.cursor()
            sql = "SELECT * FROM mahasiswa WHERE npm LIKE %s"
            cursor.execute(sql, (f"%{keyword}%",))
            result = cursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))
        except mc.Error as e:
            QMessageBox.critical(None, "Error", f"Gagal mencari data: {e}")

    def on_table_item_clicked(self, row, column):
        try:
            # Ambil data dari tabel berdasarkan baris yang diklik
            npm = self.tableWidget.item(row, 0).text()
            nama = self.tableWidget.item(row, 1).text()
            kelas = self.tableWidget.item(row, 2).text()
            jurusan = self.tableWidget.item(row, 3).text()
            tanggal_lahir = self.tableWidget.item(row, 4).text()

            # Isi form input dengan data yang diambil
            self.lineEditNPM.setText(npm)
            self.lineEditNAMA.setText(nama)
            self.lineEditKelas.setText(kelas)
            self.lineEditJurusan.setText(jurusan)
            self.lineEditTanggalLahir.setText(tanggal_lahir)
        except Exception as e:
            QMessageBox.critical(None, "Error", f"Gagal memuat data ke form: {e}")


    def clear_form(self):
        self.lineEditNPM.clear()
        self.lineEditNAMA.clear()
        self.lineEditKelas.clear()
        self.lineEditJurusan.clear()
        self.lineEditTanggalLahir.clear()



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.QlabelNPM.setText(_translate("Form", "NPM"))
        self.QlabelNama.setText(_translate("Form", "Nama"))
        self.QlabelKelas.setText(_translate("Form", "Kelas"))
        self.QlabelJurusan.setText(_translate("Form", "Jurusan"))
        self.QlabelTanggalLahir.setText(_translate("Form", "Tanggal Lahir"))
        self.pushButtonTambahkan.setText(_translate("Form", "Tambahkan"))
        self.pushButtonHapus.setText(_translate("Form", "Hapus"))
        self.pushButtonUbah.setText(_translate("Form", "Ubah"))
        self.pushButtonLoad.setText(_translate("Form", "Load"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "NPM"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nama"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Kelas"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Jurusan"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Tanggal Lahir"))
        self.pushButtonSearch.setText(_translate("Form", "Search"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
